/**
 * Master Pengguna SIMKUR — 86 Guru Sesuai SK Pembagian Tugas TP 2026/2027
 */
window.SIMKUR_AUTH_USERS = [
  {
    "nip": "197308022000122003",
    "name": "Rusnani, S.Pd., M.T",
    "role": "waka",
    "title": "Wakil Kepala Sekolah Bidang Kurikulum",
    "department": "AKL",
    "subject": "Komputer Akuntansi",
    "targetScreen": "dashboard",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Pimpinan & Tim Pengembang Kurikulum"
  },
  {
    "nip": "3153750649300003",
    "name": "Agustin Purnomosari, S.Pd., M.Pd",
    "role": "kepsek",
    "title": "Kepala SMKN 1 Banjarmasin",
    "department": "Manajemen",
    "subject": "Kepala Sekolah",
    "targetScreen": "laporan",
    "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80",
    "category": "Pimpinan Sekolah"
  },
  {
    "nip": "8554762663130202",
    "name": "Andry Dharmawan",
    "role": "admin",
    "title": "Admin Kurikulum | Operator TU",
    "department": "Tata Usaha",
    "subject": "Sinkronisasi Dapodik & Layanan Akademik",
    "targetScreen": "admin",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Tata Usaha"
  },
  {
    "nip": "ASESOR-DUDI-882190",
    "name": "Ir. Hendri Gunawan",
    "role": "asesor",
    "title": "Asesor Industri DUDI (PT Telkom)",
    "department": "TJKT",
    "subject": "Asesor Penguji LSP-P1 BNSP & Mitra Industri",
    "targetScreen": "ukk",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
    "category": "Mitra Industri"
  },
  {
    "nip": "198801102022211001",
    "name": "Muhammad Ihsan, S.Kom",
    "role": "kajur",
    "title": "Kajur / Kaprog TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Konsentrasi Keahlian TJKT (TJKN), Dasar-dasar TJKT 3",
    "targetScreen": "kurikulum",
    "avatar": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=160&q=80",
    "category": "Ketua Jurusan (TJKT)"
  },
  {
    "nip": "199305162022211001",
    "name": "Hendra Surya Pratama, S.Kom",
    "role": "kajur",
    "title": "Kajur / Kaprog DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Fotografi, Mapel Pilihan (Desain Grafis)",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Ketua Jurusan (DKV)"
  },
  {
    "nip": "198910262015032002",
    "name": "Oky Wulan Maulina, S.Pd",
    "role": "kajur",
    "title": "Kajur / Kaprog AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Praktikum Ak. Pers Jasa, Dagang & Manufaktur, Dasar Akuntansi (Akuntansi Dasar), Administrasi Pajak",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Ketua Jurusan (AKL)"
  },
  {
    "nip": "198912152024211025",
    "name": "Akhmad Hanafi Maulana, S.E",
    "role": "kajur",
    "title": "Kajur / Kaprog MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Pengelolaan SDM, Pengelolaan Sarpras, Teknologi Perkantoran, IPAS",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Ketua Jurusan (MPLB)"
  },
  {
    "nip": "198809172014022001",
    "name": "Futri Indri Septiani, S.Pd",
    "role": "kajur",
    "title": "Kajur / Kaprog Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Digital Branding",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Ketua Jurusan (Pemasaran)"
  },
  {
    "nip": "198906092025211023",
    "name": "Ahmad Gajali, M.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas X-D AKL | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "199504102023211007",
    "name": "Akbar Gazali, S.Pd",
    "role": "guru",
    "title": "Guru TJKT • Pembina Klub TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Konsentrasi Keahlian TKJ 4 (Firewall / Jaringan)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "197102081998032003",
    "name": "Amnah, M.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Klub Olahraga & Kesehatan | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Jasmani, Olahraga dan Kesehatan (PJOK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "197306092006042008",
    "name": "Dahliana, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Bahasa Inggris & Bahasa Asing Lainnya | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Inggris & Bahasa Asing Lainnya",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "5752767669300002",
    "name": "Denis Ade Priageng Prasetyo, S.Pd., M.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Keagamaan, Wali Kelas X-C TJKT | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "199404272023212021",
    "name": "Deppy Afiaty Putri, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas XI-B PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Digital on Boarding (MAPIL), Dasar-Dasar Pemasaran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199507022025212027",
    "name": "Devvy Anggriani, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas X-A PM, Pengelola Adhiwiyata | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "IPAS",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198609072025212029",
    "name": "Dina Fitriyah, S.Pd.I., M.Pd",
    "role": "guru",
    "title": "Guru Mapel Pendidikan Agama dan Budi Pekerti | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199206082022211002",
    "name": "Eddy Noor Adha, S.Kom",
    "role": "guru",
    "title": "Guru DKV • Pembina PMR | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Komputer Grafis (Dasar), Fotografi Dasar, Desain Grafis, Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199208272024212038",
    "name": "Elvasari, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas X-B TJKT | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Sejarah Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "7043780681230003",
    "name": "Ghina Aulia, S.Pd",
    "role": "guru",
    "title": "Guru BK • Staf Kesiswaan | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "196612311997022002",
    "name": "Ginem Sugiarti, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Bahasa Indonesia | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199302052022212006",
    "name": "Hamdiah, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas XII-A PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, KIK Pemasaran, Mapel Pilihan (Digital Branding)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199607252025211097",
    "name": "Hasnan Azmi, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Matematika | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Matematika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198207242022212001",
    "name": "Hatipah, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas XI-B PM | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "197312022022212001",
    "name": "Herlina Sari, S.Hut, S.Kom",
    "role": "guru",
    "title": "Guru DKV • Wali Kelas XII-A DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Desain Grafis, Fotografi, Mapel Pilihan (Fotografi Lanjutan), Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198402282010012016",
    "name": "Ida Mardiyana, S.Kom",
    "role": "guru",
    "title": "Guru DKV • Wali Kelas XI-B DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Videografi, Desain Grafis",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "197807092014061003",
    "name": "Ihsan Muzakki, SE",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Konsentrasi Keahlian TJKT (Administrasi Sistem Jaringan / ASJ)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199202192025212021",
    "name": "Irma Rutina, S.Pd.I",
    "role": "guru",
    "title": "Guru Mapel Pendidikan Agama dan Budi Pekerti | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "197202201999032003",
    "name": "Hj. Isna Yuliawati, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Pengelolaan Humas & Keprotokolan, Pilihan (Event Organizer), Pengelolaan Adm. Umum",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199604282025211020",
    "name": "Jamaluddin, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Bahasa Indonesia, Wali Kelas X-A TJKT | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198007152022211005",
    "name": "Juhdi Amrullah, S.Pd",
    "role": "guru",
    "title": "Guru BK • Ketua BKK | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "7548777678230083",
    "name": "Khumayroh, S.Psi",
    "role": "guru",
    "title": "Guru BK • Staf Kesiswaan | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "197812012008012015",
    "name": "Laili Normas, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Drumband, Wali Kelas X-C AKL | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Jasmani, Olahraga dan Kesehatan (PJOK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198303042006042017",
    "name": "Lasmaria Verawati, S.Pd",
    "role": "guru",
    "title": "Guru AKL • Wali Kelas XII-B AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Komputer Akuntansi, Praktikum Ak. Pers Jasa, Dagang & Manufaktur, Akuntansi Keuangan",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199305022025212185",
    "name": "Lilis Anggraini, M.Kom",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Dasar TJKT 3, Konsentrasi Keahlian TKJ 3 (TLJ/Firewall), Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "197705102007011020",
    "name": "Mahfuddin, S.Pd., M.A",
    "role": "guru",
    "title": "Guru BK • Wakasek Kesiswaan & Pembinaan Karakter | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "196801031998032006",
    "name": "Hj. Mahmudah, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Akuntansi Keuangan, Praktikum Akuntansi Lembaga/Instansi Pemerintah, Administrasi Pajak",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "196802271994122005",
    "name": "Masliana, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Akuntansi Keuangan, Kreativitas Inovasi dan Kewirausahaan (KIK), Dasar-dasar AKL",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199209212022212003",
    "name": "Masnah, S.Tr.Kom",
    "role": "guru",
    "title": "Guru DKV • Wali Kelas XI-A DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Desain Multimedia (Dasar), Web & App Design",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199105262023212019",
    "name": "Maya Adelina Puspita, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Matematika | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Matematika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198106172022212008",
    "name": "Megawati, S.Kom",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Dasar TJKT 1, KIK TJKT",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199211192025212025",
    "name": "Misdawati, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Matematika | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Matematika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199001312022211001",
    "name": "Muhammad Fahrurazy, S.Pd",
    "role": "guru",
    "title": "Guru Mapel PPKn | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "PPKn",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199307102019031007",
    "name": "Muhammad Jayaguna, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Pemrograman (Mapel Pilihan TJKT), Dasar TJKT 1, Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "1847778679130052",
    "name": "Muhammad Nawier Syahrowardi Maarif, S.Pd",
    "role": "guru",
    "title": "Guru Bimbingan dan Konseling (BK) | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Bimbingan Konseling"
  },
  {
    "nip": "198403212022211001",
    "name": "Muhammad Yusri, S.Pd",
    "role": "guru",
    "title": "Guru BK • Pembina Pramuka Putra | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "199008302023212023",
    "name": "Muliyani Yohana, S.Pd",
    "role": "guru",
    "title": "Guru AKL • Pembina Klub Akuntansi, Wali Kelas X-A AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Dasar Akuntansi (Akuntansi Dasar), Prak Ak Pers Jasa, Dagang & Manufaktur, KIK Pemasaran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "200006202025212026",
    "name": "Muthia Isma Annisa, S.Pd",
    "role": "guru",
    "title": "Guru Bimbingan dan Konseling (BK) | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan dan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Bimbingan Konseling"
  },
  {
    "nip": "199503222019032023",
    "name": "Mutia Paramitha, S.Kom",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Pemrograman (Mapel Pilihan TJKT), KIK TJKT, Dasar-dasar TJKT 2",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "196812132005011004",
    "name": "Muttaqin, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Bahasa Inggris dan Bahasa Asing Lainnya | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Inggris dan Bahasa Asing Lainnya",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199004222022211002",
    "name": "Nabil, S.Kom",
    "role": "guru",
    "title": "Guru DKV • Waka HUMAS, Pembina Klub Cosplay | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Komputer Grafis DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "5960777678230102",
    "name": "Naila Rahmah Maulidiyah, S.Ag",
    "role": "guru",
    "title": "Guru Mapel Pendidikan Agama dan Budi Pekerti | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198902042023212026",
    "name": "Nelly Amelia, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas X-B PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Digital on Boarding (MAPIL), Dasar-Dasar Pemasaran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199012082025212026",
    "name": "Nia Resti Maulina, S.Pd",
    "role": "guru",
    "title": "Guru Mapel IPAS | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "IPAS",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "197112272005012005",
    "name": "Nirmala Sari, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Dasar-Dasar Pemasaran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "197701192005012010",
    "name": "Noor Kumala Dewi, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas XI-A AKL | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Matematika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "199302282025212142",
    "name": "Noor Latifah, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina OSIS | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Inggris dan Bahasa Asing Lainnya",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "196812281992032010",
    "name": "Noormin Chairat, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Sejarah Indonesia | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Sejarah Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198004232006042024",
    "name": "Nurfitriana, S.Pd",
    "role": "guru",
    "title": "Guru BK • Koordinator BK | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "198906052023212031",
    "name": "Nurlisa Hayani, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas X-C DKV | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Pancasila",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "196903022014062003",
    "name": "Hj. Rachmah, S.Kom",
    "role": "guru",
    "title": "Guru DKV • Wali Kelas XI-C DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Mapel Pilihan (Konten Kreator), Mapel Pilihan (Animasi), Videografi, KIK DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198003092007012012",
    "name": "Rahmiana, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Matematika | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Matematika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199607302019032015",
    "name": "Rema Maulinda Lestari, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Kesenian, Wali Kelas X-B DKV | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Seni Budaya, KIK MPLB & DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "196808121999032007",
    "name": "Dra. Rentaida Hutagalung",
    "role": "guru",
    "title": "Guru Kejuruan AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Kreativitas Inovasi dan Kewirausahaan (KIK), Dasar-Dasar AKL",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "198401022009032009",
    "name": "Rini Suciati, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas XI-A PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Mapel Pilihan (Digital Branding)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198103162022212010",
    "name": "Risa Rusniarti, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas XII-C PM | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "199809292025212031",
    "name": "Siti Aisyah, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Desain Multimedia (Dasar), Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198404042025212051",
    "name": "Siti Arbayani, S.Pd.I",
    "role": "guru",
    "title": "Guru Umum • Wali Kelas X-B AKL, Pengelola Adhiwiyata | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198811032022212003",
    "name": "Siti Khairiyah, S.Pd",
    "role": "guru",
    "title": "Guru AKL • Wali Kelas XII-C AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Komputer Akuntansi, Praktik Ak. Pers Jasa, Dagang & Manufaktur, Dasar Akuntansi (Akuntansi Dasar), KIK AKL",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "196711061994122006",
    "name": "Dra. Hj. Siti Noor Hafizah",
    "role": "guru",
    "title": "Guru Mapel Bahasa Indonesia | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Indonesia",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199408132025212029",
    "name": "Siti Rahmah, S.Pd",
    "role": "guru",
    "title": "Guru Mapel IPAS | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "IPAS",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198307262022211003",
    "name": "Suaidi Rahman, S.Pd",
    "role": "guru",
    "title": "Guru Bimbingan dan Konseling (BK) | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Bimbingan Konseling"
  },
  {
    "nip": "197411252005012008",
    "name": "Susi Kartika Dewi, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Pembina Debat Bahasa Inggris, Wali Kelas X-C PM | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Inggris dan Bahasa Asing Lainnya",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "196701211994031005",
    "name": "Syarifuddin, S.Pd",
    "role": "guru",
    "title": "Guru Umum • Waka Sarpras | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "PPKn",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "197207082006042006",
    "name": "Taibah, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Bahasa Inggris dan Bahasa Asing Lainnya | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Bahasa Inggris dan Bahasa Asing Lainnya",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198103192022211001",
    "name": "Topan Borneo Angkasa Negara, S.Pd",
    "role": "guru",
    "title": "Guru BK • Ketua TPPK, Pembina Paskibra | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "197811012025212023",
    "name": "Triana Novita, S.Sos",
    "role": "guru",
    "title": "Guru Kejuruan MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Ekonomi Bisnis, Komunikasi di Tempat Kerja, Grooming (Mapel Pilihan), Pendidikan Pancasila",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "197701262022211002",
    "name": "Tusamsi, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Teknologi Perkantoran, Pengelolaan Rapat, Pengelolaan Keuangan Sederhana, Dasar MPLB, KIK MPLB",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "198110042022211004",
    "name": "Widi Sigit Nugroho, S.Pd",
    "role": "guru",
    "title": "Guru Kejuruan TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Konsentrasi Keahlian TKJ 2 (Administrasi Infrastruktur Jaringan / AIJ)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199310122025212024",
    "name": "Widya Savitri, S.Pd",
    "role": "guru",
    "title": "Guru Mapel Seni Budaya | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Seni Budaya, KIK MPLB & DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "198407132022212011",
    "name": "Wirdatus Sa'yah, S.Pd",
    "role": "guru",
    "title": "Guru BK • Pembina Pramuka Putri | SMKN 1 Banjarmasin",
    "department": "BK",
    "subject": "Bimbingan Konseling (BK)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru BK"
  },
  {
    "nip": "197005282024212004",
    "name": "Wiwiek Hastutie, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas XII-D PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Digital on Boarding (MAPIL)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "9851761662230192",
    "name": "Yosievine Margareth Kolriry",
    "role": "guru",
    "title": "Guru Mapel Pendidikan Agama Kristen | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama Kristen, Baca Tulis Alkitab (Mulok)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  },
  {
    "nip": "199704072022212003",
    "name": "Yunada Afriliani, S.Pd",
    "role": "guru",
    "title": "Guru Pemasaran • Wali Kelas XI-C PM | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran, Mapel Pilihan Pemasaran, Informatika",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199403152024212015",
    "name": "Della Safitri",
    "role": "guru",
    "title": "Guru Produktif AKL",
    "department": "AKL",
    "subject": "Spreadsheet & Akuntansi Keuangan",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198705122022212008",
    "name": "Hairita Indriati, S.Pd",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Kearsipan & Komunikasi Tempat Kerja",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "197209142005012006",
    "name": "Hj. Asmiani",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Dasar Manajemen Perkantoran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198811202022212011",
    "name": "Leni Meldawati",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Ekonomi Bisnis & Administrasi Umum",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198207182010012014",
    "name": "Thaibah, S.Pd",
    "role": "guru",
    "title": "Guru Bahasa Inggris TJKT",
    "department": "TJKT",
    "subject": "Bahasa Inggris Kejuruan TJKT",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Muatan Nasional"
  },
  {
    "nip": "198506222014032003",
    "name": "Wahidah, S.Pd.I",
    "role": "guru",
    "title": "Guru Mapel Pendidikan Agama dan Budi Pekerti | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Pendidikan Agama dan Budi Pekerti, Mulok (Pend. Alquran)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Mapel Umum"
  }
];
