// Data Direktori Akun Otentikasi Resmi SMKN 1 Banjarmasin (90 Akun Terdaftar)
window.SIMKUR_AUTH_USERS = [
  {
    "nip": "197308022000122003",
    "name": "Rusnani",
    "role": "waka",
    "title": "Waka Kurikulum SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Praktikum Akuntansi Perusahaan & Perpajakan",
    "targetScreen": "dashboard",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Pimpinan & Manajemen"
  },
  {
    "nip": "3153750649300003",
    "name": "Agustin Purnomosari",
    "role": "kepsek",
    "title": "Kepala Sekolah SMKN 1 Banjarmasin",
    "department": "Manajemen",
    "subject": "Kepala Sekolah & Supervisi Manajerial",
    "targetScreen": "laporan",
    "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80",
    "category": "Pimpinan & Manajemen"
  },
  {
    "nip": "8554762663130202",
    "name": "Andry Dharmawan",
    "role": "admin",
    "title": "Admin Kurikulum | Operator TU",
    "department": "Tata Usaha",
    "subject": "Sinkronisasi Dapodik & Layanan Akademik",
    "targetScreen": "admin",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Tata Usaha"
  },
  {
    "nip": "ASESOR-DUDI-882190",
    "name": "Ir. Hendri Gunawan",
    "role": "asesor",
    "title": "Asesor Industri DUDI (PT Telkom)",
    "department": "TJKT",
    "subject": "Asesor Penguji LSP-P1 BNSP & Mitra Industri",
    "targetScreen": "ukk",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
    "category": "Mitra Industri"
  },
  {
    "nip": "198801102022211001",
    "name": "Muhammad Ihsan",
    "role": "kajur",
    "title": "Kajur Teknik Jaringan Komputer & Telekomunikasi (TJKT)",
    "department": "TJKT",
    "subject": "Konsentrasi Keahlian TJKT & TeFa",
    "targetScreen": "kurikulum",
    "avatar": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=160&q=80",
    "category": "Kepala Program Keahlian"
  },
  {
    "nip": "199305162022211001",
    "name": "Hendra Surya Pratama",
    "role": "kajur",
    "title": "Kajur Desain Komunikasi Visual (DKV)",
    "department": "DKV",
    "subject": "Konsentrasi Keahlian DKV & TeFa",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Kepala Program Keahlian"
  },
  {
    "nip": "198910262015032002",
    "name": "Oky Wulan Maulina",
    "role": "kajur",
    "title": "Kajur Akuntansi & Keuangan Lembaga (AKL)",
    "department": "AKL",
    "subject": "Konsentrasi Keahlian AKL & TeFa",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Kepala Program Keahlian"
  },
  {
    "nip": "198912152024211025",
    "name": "Akhmad Hanafi Maulana, SE",
    "role": "kajur",
    "title": "Kajur Manajemen Perkantoran & Layanan Bisnis (MPLB)",
    "department": "MPLB",
    "subject": "Konsentrasi Keahlian MPLB & TeFa",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Kepala Program Keahlian"
  },
  {
    "nip": "198809172014022001",
    "name": "Futri Indri Septiani",
    "role": "kajur",
    "title": "Kajur Bisnis Digital & Pemasaran",
    "department": "Pemasaran",
    "subject": "Konsentrasi Keahlian Pemasaran & TeFa",
    "targetScreen": "kurikulum",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Kepala Program Keahlian"
  },
  {
    "nip": "198906092025211023",
    "name": "Ahmad Gajali",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199504102023211007",
    "name": "Akbar Gazali",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "197102081998032003",
    "name": "Amnah, M. PD",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "197306092006042008",
    "name": "Dahliana, S. Pd",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "5752767669300002",
    "name": "DENIS ADE PRIAGENG PRASETYO",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199404272023212021",
    "name": "Deppy Afiaty Putri",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199507022025212027",
    "name": "Devvy Anggriani",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198609072025212029",
    "name": "Dina Fitriyah",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199206082022211002",
    "name": "Eddy Noor Adha",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199208272024212038",
    "name": "Elvasari",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "7043780681230003",
    "name": "GHINA AULIA",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "196612311997022002",
    "name": "Ginem Sugiarti",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199302052022212006",
    "name": "Hamdiah",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199607252025211097",
    "name": "Hasynan Azmi",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198207242022212001",
    "name": "Hatipah",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "197312022022212001",
    "name": "Herlina Sari",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198402282010012016",
    "name": "Ida Mardiyana",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "197807092014061003",
    "name": "Ihsan Muzakki, SE",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199202192025212021",
    "name": "Irma Rutina",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "197202201999032003",
    "name": "Isna Yuliawati",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199604282025211020",
    "name": "Jamaluddin",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "198007152022211005",
    "name": "Juhdi Amrullah",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Dasar-Dasar Keahlian AKL",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "7548777678230083",
    "name": "Khumayroh",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "197812012008012015",
    "name": "Laili Normas",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "198303042006042017",
    "name": "Lasmaria Verawati",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199305022025212185",
    "name": "LILIS ANGGRAINI, S.KOM. M.KOM",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "197705102007011020",
    "name": "Mahfuddin",
    "role": "guru",
    "title": "Guru Pengampu Umum | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Mata Pelajaran Umum (Beban Waka 12 JP)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "196801031998032006",
    "name": "MAHMUDAH, S.PD, MM",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "196802271994122005",
    "name": "Masliana",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199209212022212003",
    "name": "Masnah",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199105262023212019",
    "name": "Maya Adelina Puspita",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "198106172022212008",
    "name": "Megawati, S.kom",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199211192025212025",
    "name": "Misdawati",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199001312022211001",
    "name": "Muhammad Fahrurazy",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199307102019031007",
    "name": "Muhammad Jayaguna",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "1847778679130052",
    "name": "MUHAMMAD NAWIER SYAHROWARDI MAARIEF",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198403212022211001",
    "name": "Muhammad Yusri",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Dasar-Dasar Keahlian TJKT",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199008302023212023",
    "name": "Muliyani Yohana",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "200006202025212026",
    "name": "Muthia Isma Annisa",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199503222019032023",
    "name": "Mutia Paramitha",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Dasar-Dasar Keahlian DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "196812132005011004",
    "name": "Muttaqin",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199004222022211002",
    "name": "Nabil",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Mata Pelajaran Pemasaran (Beban Waka 12 JP)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "5960777678230102",
    "name": "Naila Rahmah Maulidiyah",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "198902042023212026",
    "name": "Nelly Amelia",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199012082025212026",
    "name": "Nia Resti Maulina",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "197112272005012005",
    "name": "Nirmala Sari, S.Pd",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "197701192005012010",
    "name": "Noor Kumala Dewi",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "199302282025212142",
    "name": "Noor Latifah",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Dasar-Dasar Keahlian Pemasaran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "196812281992032010",
    "name": "Noormin Chairat",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "198004232006042024",
    "name": "Nurfitriana",
    "role": "guru",
    "title": "Guru Pengampu Umum | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Produktif Umum & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198906052023212031",
    "name": "Nurlisa Hayani",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "196903022014062003",
    "name": "RACHMAH",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198003092007012012",
    "name": "Rahmiana",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199607302019032015",
    "name": "Rema Maulinda Lestari",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Dasar-Dasar Keahlian DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "196808121999032007",
    "name": "Rentaida Hutagalung",
    "role": "guru",
    "title": "Guru Pengampu Umum | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Produktif Umum & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "198401022009032009",
    "name": "Rini Suciati",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198103162022212010",
    "name": "Risa Rusniarti",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199809292025212031",
    "name": "Siti Aisyah",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "198404042025212051",
    "name": "SITI ARBAYANI",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "198811032022212003",
    "name": "Siti Khairiyah, S.pd",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Produktif AKL & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "196711061994122006",
    "name": "Siti Noor Hafizah",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Produktif DKV & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "199408132025212029",
    "name": "Siti Rahmah",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "198307262022211003",
    "name": "Suaidi Rahman",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "197411252005012008",
    "name": "Susi Kartika Dewi",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "196701211994031005",
    "name": "Syarifuddin",
    "role": "guru",
    "title": "Guru Pengampu Umum | SMKN 1 Banjarmasin",
    "department": "Umum",
    "subject": "Mata Pelajaran Umum (Beban Waka 12 JP)",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Umum"
  },
  {
    "nip": "197207082006042006",
    "name": "Taibah, S. Pd",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "198103192022211001",
    "name": "Topan Borneo Angkasa Negara",
    "role": "guru",
    "title": "Guru Pengampu DKV | SMKN 1 Banjarmasin",
    "department": "DKV",
    "subject": "Dasar-Dasar Keahlian DKV",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru DKV"
  },
  {
    "nip": "197811012025212023",
    "name": "Triana Novita",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "197701262022211002",
    "name": "Tusamsi",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "198110042022211004",
    "name": "Widi Sigit Nugroho",
    "role": "guru",
    "title": "Guru Pengampu TJKT | SMKN 1 Banjarmasin",
    "department": "TJKT",
    "subject": "Produktif TJKT & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru TJKT"
  },
  {
    "nip": "199310122025212024",
    "name": "Widya Savitri",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Dasar-Dasar Keahlian MPLB",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "198407132022212011",
    "name": "WIRDATUSSA'YAH",
    "role": "guru",
    "title": "Guru Pengampu AKL | SMKN 1 Banjarmasin",
    "department": "AKL",
    "subject": "Dasar-Dasar Keahlian AKL",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru AKL"
  },
  {
    "nip": "197005282024212004",
    "name": "Wiwiek Hastutie",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "9851761662230192",
    "name": "Yosievine Margareth Kolriry",
    "role": "guru",
    "title": "Guru Pengampu MPLB | SMKN 1 Banjarmasin",
    "department": "MPLB",
    "subject": "Produktif MPLB & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru MPLB"
  },
  {
    "nip": "199704072022212003",
    "name": "Yunada Afriliani",
    "role": "guru",
    "title": "Guru Pengampu Pemasaran | SMKN 1 Banjarmasin",
    "department": "Pemasaran",
    "subject": "Produktif Pemasaran & Binaan Rombel",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Dewan Guru Pemasaran"
  },
  {
    "nip": "199403152024212015",
    "name": "Della Safitri",
    "role": "guru",
    "title": "Guru Produktif AKL",
    "department": "AKL",
    "subject": "Spreadsheet & Akuntansi Keuangan",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198705122022212008",
    "name": "Hairita Indriati, S.Pd",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Kearsipan & Komunikasi Tempat Kerja",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "197209142005012006",
    "name": "Hj. Asmiani",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Dasar Manajemen Perkantoran",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198811202022212011",
    "name": "Leni Meldawati",
    "role": "guru",
    "title": "Guru Produktif MPLB",
    "department": "MPLB",
    "subject": "Ekonomi Bisnis & Administrasi Umum",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Guru Pengampu"
  },
  {
    "nip": "198207182010012014",
    "name": "Thaibah, S.Pd",
    "role": "guru",
    "title": "Guru Bahasa Inggris TJKT",
    "department": "TJKT",
    "subject": "Bahasa Inggris Kejuruan TJKT",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Muatan Nasional"
  },
  {
    "nip": "198506222014032003",
    "name": "Wahidah, S.Pd.I",
    "role": "guru",
    "title": "Guru Pend. Agama Pemasaran",
    "department": "Pemasaran",
    "subject": "Pendidikan Agama & Budi Pekerti",
    "targetScreen": "portal-guru",
    "avatar": "assets/teacher_avatar.jpg",
    "category": "Muatan Nasional"
  }
];
